### PR TITLE
Make default settings values public

### LINKED ISSUE #185: Consider making AzureStorageAttachmentConfiguration settings public
Consider making the settings that can be provided through the constructors of [`AzureStorageAttachmentConfiguration`](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/develop/src/ServiceBus.AttachmentPlugin/AzureStorageAttachmentConfiguration.cs) `public` instead of `internal`. This way it's easy to reuse a configuration when implementing clean up.

In particular the following settings would be nice to have access to

- [`ConnectionStringProvider`](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/08aca98974af5752b8ff01530464e758cf7e0c24/src/ServiceBus.AttachmentPlugin/AzureStorageAttachmentConfiguration.cs#L106)
- [`ContainerName`](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/08aca98974af5752b8ff01530464e758cf7e0c24/src/ServiceBus.AttachmentPlugin/AzureStorageAttachmentConfiguration.cs#L108
)
- [`MessagePropertyToIdentifyAttachmentBlob`](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/08aca98974af5752b8ff01530464e758cf7e0c24/src/ServiceBus.AttachmentPlugin/AzureStorageAttachmentConfiguration.cs#L114)

For now it's one solution is to create your own class (like below), that holds the settings, and use that as input to both the `AzureStorageAttachmentConfiguration` and the clean up routine. Making the settings public will eliminate this boilerplate code.

```
public class AzureStorageSettings
{
    public string ConnectionString { get; set; }
    public string ContainerName { get; set; }
    public string MessagePropertyToIdentifyAttachmentBlob { get; set; }
}
```

See Pull Request #189

### PR DESCRIPTION
**Pull request by sorenhansen**
Closes #185

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBus.AttachmentPlugin 0.0.757-preview failed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/builds/32079323) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/c9502c9f2f by @)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBus.AttachmentPlugin 0.0.758-preview completed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/builds/32079498) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/36896f480a by @)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBus.AttachmentPlugin 0.0.759-preview completed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/builds/32079533) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/6327568368 by @)

**Comment by SeanFeldman** [comment]
@sorenhansen do you mind to rewrite the history to get rid of the unnecessary earlier commits?

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBus.AttachmentPlugin 0.0.760-preview completed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/builds/32081437) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/74b1b56769 by @)

**Comment by sorenhansen** [comment]
Sorry, I screwed up trying to rewrite the git history... :-/

I created PR #189 instead

Hope it's ok?

**Comment by SeanFeldman** [comment]
No worries. That works as well.

**Pull request closed without merging**
