### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by SimonCropp**
I tried to split each change into a re-usable piece that u can optionally copy into the master.

So this PR should not necessarily be considered an option for a full merge.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBus.AttachmentPlugin 0.0.12-preview failed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/build/0.0.12-preview) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/65112fdad5 by @SimonCropp)

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBus.AttachmentPlugin 0.0.13-preview failed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/build/0.0.13-preview) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/14d0d45d50 by @SimonCropp)

**Comment by SimonCropp** [comment]
note i did this PR in complete ignorance of how azure servicebus plugins work ;)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBus.AttachmentPlugin 0.0.14-preview completed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/build/0.0.14-preview) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/558457d165 by @SeanFeldman)

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBus.AttachmentPlugin 0.0.15-preview completed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/build/0.0.15-preview) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/da07511e8d by @SeanFeldman)

**Comment by SeanFeldman** [comment]
Thank you @SimonCropp  ❤️

**Pull request merged**
